kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name:  {{ .Chart.Name }}
spec:
  to:
    kind: Service
    name:  {{ .Chart.Name }}
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None